### ISSUE TITLE
Erro teste

### ISSUE THREAD

**Issue by GabrielL915** [GeanCCZ/Ecom-Back#1]
criar mock para os teste unitário e seguir o fluxo do método que for testar

    @InjectMocks
    private BrandService brandService;

    @Mock
    private BrandRepository brandRepository;

    @Mock
    private CRUDRepository<Brand, BrandDTO> repository;

    @Mock
    private Adapter<Brand, BrandDTO> brandAdapter;

    @Test
    void testBrandCreate() {
        BrandDTO brandDTO = new BrandDTO(null, "Brand", "A new way to search your thoughts", null, null);
        Brand newBrand = new Brand();

        newBrand.setId(brandDTO.id());

        //outros campos

        when(brandAdapter.fromDto(any(BrandDTO.class))).thenReturn(newBrand);
        //segue as proximas etapas do metodo se tiver

        when(repository.save(any(Brand.class))).thenReturn(newBrand);

        brandService.create(brandDTO);

        verify(repository).save(newBrand);
        verify(brandAdapter).fromEntity(newBrand);
    }

**Comment by GeanCCZ** [comment]
Obrigado!
